//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppaLiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public string Estado { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public int PrestamoId { get; set; }
    
        public virtual Local Destino { get; set; }
    }
}
